# Generated by Django 5.1.1 on 2024-09-13 17:04

from django.db import migrations


def add_admin_user(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.create_superuser(username='admin',
                                        password='admin',
                                        email='admin@localhost')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_admin_user)
    ]
